language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
before_install:
    - cpanm Dist::Zilla
    - dzil authordeps --missing | cpanm
    - dzil listdeps --missing | cpanm
script: "dzil test"
