language: perl
perl:
    - "5.10"
    #- "5.12"
    #- "5.14"
    - "5.16"
install:
    # Install Dist::Zilla dependencies quickly
    - sudo apt-get install libdist-zilla-perl
    - cpanm Dist::Zilla
    - dzil authordeps --missing | cpanm
    - dzil listdeps --missing | cpanm
script: "dzil test --author --release"
